x-environment: &environment
  MYSQL_HOST: db
  MYSQL_USER: root
  MYSQL_PASSWORD: root
  MYSQL_DB_LOG: raplog
  MYSQL_DB_AUTOREPORT: autoreport
  FALK_APP_ID: 80
  FALK_EXTENDED_USER_RIGHTS: "[{\"A\":80,\"R\":\"LC\",\"U\":1},{\"A\":80,\"R\":\"SC\",\"U\":2},{\"A\":81,\"R\":\"LC\",\"U\":2}]"
  USERORGID: "pilot"
  SHINYPROXY_USERNAME: test@tester.no
  SHINYPROXY_USERGROUPS: "pilot"


services:
  db:
    image: mysql:8
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./dev/db:/docker-entrypoint-initdb.d

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: "linux/amd64"
    environment:
      MSSQL_SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    volumes:
      - ./dev/mssql/init.sql:/db/init.sql
      - ./dev/mssql/entrypoint.sh:/entrypoint.sh
    entrypoint: ["/bin/bash", "/entrypoint.sh"]

  app:
    image: rapporteket/rapregtemplate:main
    ports:
      - 3838:3838
    environment:
      << : *environment
    platform: "linux/amd64"

  dev:
    depends_on:
      - db
      - mssql
    image: rapporteket/rstudio:main
    volumes:
      - ~/.ssh:/home/rstudio/.ssh
      - ~/.gitconfig:/home/rstudio/.gitconfig
      - ../rapbase/.:/home/rstudio/rapbase
      - .:/home/rstudio/rapregtemplate
    ports:
      - "8787:8787"
    restart: "no"
    environment:
      << : *environment
      DISABLE_AUTH: "true"
      FALK_EXTENDED_USER_RIGHTS: "[{\\\"A\\\":80,\\\"R\\\":\\\"LC\\\",\\\"U\\\":1},{\\\"A\\\":80,\\\"R\\\":\\\"SC\\\",\\\"U\\\":2},{\\\"A\\\":81,\\\"R\\\":\\\"LC\\\",\\\"U\\\":2}]"

  adminer:
    depends_on:
      - db
      - mssql
    image: adminer
    restart: "no"
    environment:
      ADMINER_PLUGINS: frames
    ports:
      - 8888:8080
